Constants/Permissions.js
RCTAppleHealthKit.xcodeproj/project.pbxproj
RCTAppleHealthKit/RCTAppleHealthKit+Methods_LabTests.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_LabTests.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/getBloodAlcoholContentSamples().md
docs/getLatestBloodAlcoholContent().md
index.d.ts

Added BloocAlcoholContent quantity type. Added also some of the missing typescript types.

Added BloodAlcoholContent

---

RCTAppleHealthKit/RCTAppleHealthKit.m
docs/README.md
index.d.ts

Finish the implementation of getDailyDistanceSwimmingSamples() and update the README to include this.

Complete the implementation of getDailyDistanceSwimmingSamples

---

README.md

Add the Capabilities settings to the 'Getting Started' section

Add Xcode Capabilities Documentation

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/getDistanceSwimming.md
index.d.ts

The getDistanceSwimming method was mentioned in the documentation, however it hadn't been implemented and the referenced documentation was missing.

Add methods and documentation for getDistanceSwimming

---

index.d.ts

getDailyStepCountSamples is returning an array

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Activity.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Activity.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
README.md
docs/README.md
docs/getAppleStandTime.md
docs/permissions.md
index.d.ts
src/constants/Permissions.js

I have implemented AppleStandTime and updated the documentation to include this

Implement AppleStandTime

---

RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/README.md
docs/getAuthStatus.md
index.d.ts

Fixes an issue where a function name was wrong. Also updates the types
for getAuthStatus to reflect what actually is needed for this function
to work.

fix(getauthorizationstatus): fix getAuthorizationStatus failing

---

docs/getAuthStatus.md
index.d.ts

fix: fix an incorrect typescript definition

---

docs/permissions.md
index.d.ts
src/constants/Permissions.js

feat: add Distance Swimming permission

---

docs/saveWorkout.md

docs: add saveWorkout documentation

---

docs/saveFood.md

docs: add docs to saveFood method

---

docs/saveBloodAlcoholContent.md
docs/saveBloodGlucoseSample.md

docs: add docs to save blood alcohol/glucose

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Results.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Results.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/getCarbohydratesSamples.md
docs/saveCarbohydratesSample.md
index.d.ts

feat: get and save carbohydrate samples

---

docs/getBloodAlcoholContentSamples.md
docs/getBloodGlucoseSamples.md
docs/getBloodPressureSamples.md
docs/getBodyTemperatureSamples.md
docs/getCarbohydratesSamples.md
docs/getDailyDistanceSwimmingSamples.md
docs/getHeartRateSamples.md
docs/getHeartRateVariabilitySamples.md
docs/getHeightSamples.md
docs/getOxygenSaturationSamples.md
docs/getRespiratoryRateSamples.md
docs/getRestingHeartRateSamples.md
docs/getSleepSamples.md
docs/getVo2MaxSamples.md
index.d.ts

update return type to Array on Samples
Fixes #33 

fix: update return type to Array on Samples

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Activity.m
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Body.m
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.m

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #25

Fixed poor error handling in some functions

---

RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m

Includes proper keys for read permissions in `getReadPermFromText` regarding Nutrition Data stored in Health.
Fixes #72

Include Nutrition data in getReadPermFromText

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Mindfulness.m

I noticed a typo when browsing the contents of the library.

Fix Methods_Mindfulness typo

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
SUMMARY.md
docs/README.md
docs/getHeartbeatSeriesSamples.md
docs/permissions.md
index.d.ts
src/constants/Permissions.js

Adds support for reading the HKHeartbeatSeriesSample type.  I think HealthKit allows writing this type as well, but I don't have the bandwidth to build that our right now.
Fixes #121

Add support for HKHeartbeatSeriesSample

---

index.d.ts

Type-definition fix for getWeightSamples method.

add fix type-definition getWeightSamples method

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
example/ios/Podfile
example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj

arm64 architecture default settings have to be remove in order to work on MAC M1
Example app should work on M1 settings

fix(mac-m1): example app should work on M1 settings

---

docs/getHeartbeatSeriesSamples.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

docs: Update getHeartbeatSeriesSamples.md

---

docs/getWater.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Update water.md - Removed unnecessary character

---

README.md

This PR adds the invite to the official Discord server on the README file
Fixes https://github.com/agencyenterprise/react-native-health/issues/234

Add discord invite

---

docs/saveWeight.md

Update to docs for method ```saveWeight```.

docs: improve docs

---

package.json

updated @expo/config-plugins to 6.0.1

---

v2/RNHealthKitCore/HealthKitCore/HealthKitCore.swift
v2/RNHealthKitCore/HealthKitCore/Quantity/QuantityQueries.swift
v2/RNHealthKitCore/HealthKitCore/Quantity/QuantityQueriesParameters.swift
v2/RNHealthKitCore/HealthKitCore/Quantity/QuantitySample.swift
v2/RNHealthKitCore/HealthKitCore/QueryParameters.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutQueries.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutQueryParameters.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutSample.swift
v2/RNHealthKitCore/ReactNativeBridge/RNHealthKitWrapper.swift

This PR introduces comprehensive documentation for the `HealthKitCore` module as part of the ongoing v2 rewrite.

chore: Add documentation to HealthKitCore module
