agencyenterprise/react-native-health

RCTAppleHealthKit/RCTAppleHealthKit+Utils.m

Apple keeps adding more workout types. For instance, iOS 14 added "socialDance" type.
Current implementation crashes if a new type appears. This tiny change makes sure that the crash never happens.

fix: fix crash when WorkoutActivityType is unknown

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Sleep.m
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Workout.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Workout.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/getWorkout.md

This appeared as a bug request. The library currently contains 2 ways of getting workouts that are, essentially, the same
- Via `getSamples()` method
- Via `getWorkouts()` method
The disadvantages of the second one are the following
- Lack of documentation, in comparison with the `getSamples()`
- Reduced amount of information being returned to the developer, as the first one returns "sourceName" & "sourceId"
- #20

Remove getWorkout method from the library

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m

I think manually added activities should be included by default.
If you check the old repo, there are a lot of open issues saying several methods are not working, when really the issue was they wanted to retrieve manually added data and they were not specifying that in the call.
I know the old module wasn't too much clear about it, and that's was probably part of the problem. But the fact that many people opened issues says to me that the module should retrieve manually added data by default.
Here are some of those issues
https://github.com/terrillo/rn-apple-healthkit/issues/140
https://github.com/terrillo/rn-apple-healthkit/issues/164
https://github.com/terrillo/rn-apple-healthkit/issues/155
https://github.com/terrillo/rn-apple-healthkit/issues/151

Manually added activities to be true by default

---

RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m

This appeared as a bug request. The library currently supports getting `appleExerciseTime`, however, the permissions to achieve that were removed
This PR adds the permissions back to the native library
- #22

Add permission for AppleExerciseTime

---

index.d.ts

iOS 14.2:
Some callbacks return results as array<HealthValue>, this PR corrects the typings

updated types to reflect results that present as Array

---

RCTAppleHealthKit/RCTAppleHealthKit.m

This appeared as a bug request. The library currently supports getting `getBodyFatPercentageSamples `, however, the methods for that weren't exported to the React Native client
This PR adds this ability back to the RN library
- #34

Export get and set body fat percentage methods

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Activity.m
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit.m
index.d.ts
src/constants/Units.js

Thanks for starting this repo! Happy to help out where I can. Here are a few fixes for adding common args to some sample queries I'm using to start. 
- Add kilocalorie unit
- Add `period` as an input option
- Fix return types for a few other sample queries
- Standardize options for all Activity methods
- Export missing method to use getAppleStandTime

Add KCal unit, standardize options for all Activity methods, export getAppleStandTime 

---

index.d.ts

Fix `results` type callback param for `getWeightSamples` it returns an array of object, not just an object.

FIX Typescript definition for getWeightSamples

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit+Queries.h
RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
docs/getDistanceCycling.md
docs/getDistanceSwimming.md
docs/getDistanceWalkingRunning.md
docs/getFlightsClimbed.md
docs/getStepCount.md

Add flag manually added steps

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Characteristic.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Characteristic.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
docs/README.md
docs/getBloodType.md
docs/permissions.md
index.d.ts
src/constants/Permissions.js

That PR introduces `getBloodType` method, according to [Apple documentation](https://developer.apple.com/documentation/healthkit/hkbloodtype). Also PR adds the new permission called `BloodType` to have an option to obtain the blood type.
Permission | Result
--- | ---

feat: introduce `getBloodType` method

---

RCTAppleHealthKit/RCTAppleHealthKit.h
RCTAppleHealthKit/RCTAppleHealthKit.m

Introduces self-initializing methods within the objective-c export, it allows us to call the method outside of initHealthKit. So for example instead of:
```jsx
AppleHealthKit.initHealthKit(permissions, (error: string) => {
AppleHealthKit.getSample()
}
```
This PR introduces the options to uses these functions through our codebase by calling the methods imperatively
AppleHealthKit.getAnchoredWorkouts(), like for example in a component's hook.
```jsx
useEffect(() => {
AppleHealthKit.getSample()
},[])
```
This assume that HealthKit permissions have been granted/denied. If they've been granted, the function will run and it won't if they've been denied. Adding self _initializeHealthStore will not affect users who write their functions within AppleHealthKit.initHealthKit
Please …

enhancement: Init healthkit for exported library methods.

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Dietary.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Dietary.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/getEnergyConsumedSamples.md
docs/getProteinSamples.md
index.d.ts

Added methods for accessing samples with information about energy and protein consumed.
------
I would like to mention that I am relatively new to react native, I have never written a single line of code in Objective-C & this is the first native method that I export to react native. I basically copied what was made for `getCarbohydratesSamples()` and changed the same files like the [PR for adding another new feature reagarding Blood Type](https://github.com/agencyenterprise/react-native-health/commit/1d0c791a8ad8acfa31be9c7680baf9609322eeb7).
I decided to put those methods where `saveFood()` is already put: `RCTAppleHealthKit+Methods_Dietary`. In Apple's documentation Energy Consumed and Protein are both in "Dietary". However the existing `getCarbohydratesSamples()` method is in …

Add methods for reading Dietary: Energy Consumed and Dietary: Protein

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Workout.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Workout.m
RCTAppleHealthKit/RCTAppleHealthKit+Queries.h
RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
RCTAppleHealthKit/RCTAppleHealthKit+Utils.h
RCTAppleHealthKit/RCTAppleHealthKit+Utils.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/README.md
docs/getAnchoredWorkouts.md
index.d.ts

feat(anchored-workout-query): create a workouts query using an hkanchoredobjectquery
* Adds a library method that allows to query workouts via an HKAnchoredObjectQuery, exposing a query workouts results array and a resulting base-64 encoded anchor to the react-native bridge
* Adds utility methods to create an anchored query predicate with optional base-64 encoded anchor, startDate, and endDate params
* Adds documentations, as well as typescript definitions

feat: anchored object query for workouts

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
RCTAppleHealthKit/RCTAppleHealthKit+Utils.m

While querying getSamples, elements of type `HKWorkout` and `HKQuantity` with malformed properties can crash client app with vague error `{"message":"error getting samples"}`. This is particularly related to properties such as `Dates`. Thus as an extra safety, we've included a try catch statement in the dates utils method.
With this PR, we can at least catch sample sourceId in logs, without crashing client app.

fix: error handling for malformed items in getSamples

---

index.d.ts

Just changed to type of `getBloodPressureSamples` to the corresponding one in the documentation (https://github.com/agencyenterprise/react-native-health/blob/master/docs/getBloodPressureSamples.md).
Here the value for `bloodPressureDiastolicValue` and `bloodPressureSystolicValue` is mentioned, but not listed as type, thus Typescript assumes it's wrong - yet it is working.
I chose to create a new interface for BloodPressureSamples, since the blood pressure values are only used there and nowhere else.

Fix health value types for blood pressure

---

index.d.ts

Sample `HKWorkoutQueriedSampleType` data, result of `getSamples()` with `type: 'Workout'`:
```js
[
{
activityId: 37,
activityName: "Running",
calories: 0,
device: "iPhone12,1",
distance: 0,
end: "2021-04-19T20:43:00.000+0800",
id: "7DC009CC-3B9A-4C14-B9FA-1D3880D1F07C",
metadata: { HKWasUserEntered: 1 },
sourceId: "com.apple.Health",
sourceName: "Health",
start: "2021-04-19T18:43:00.000+0800",
tracked: false,
},
]
```
Note `tracked` is a boolean.

fix(types): `tracked` should be a boolean

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Results.m
docs/saveBloodGlucoseSample.md

1. Fixes a crash when adding a blood glucose sample with a valid unit specified.
It was fixed by using one of the existing unit parsing methods.
Before the unit string was being set instead of a `HKUnit` object, which would cause a crash, when one of the object's methods was called during conversion.
2. Mapped the documented (but missing) `startDate` and `endDate` options with fallback to the undocumented `date` options, when saving a blood glucose sample.
3. Removed unused `mmoLPerL` variables.
Fixes # (new issue)

Fix crash with blood glucose unit

---

docs/saveWorkout.md

Update documentation for `saveWorkout` with required parameters for saving `totalEnergyBurned` and `totalDistance` for a workout.
Fixes #92

Add units parameters to saveWorkout docs

---

example/ios/Podfile
example/ios/Podfile.lock

The latest xcode update (12.5) caused building error in our example project, which happened in Flipper.
This PR sets the Flipper to a version in the podfile to a version which no error occurs.
Additional info: https://github.com/facebook/flipper/issues/2215

Changed flipper version on podfile to fix building error on xcode 12.5

---

README.md
app.plugin.js
docs/Expo.md
package.json

With Expo SDK 41 we've rolled out an interface called [config plugins](https://docs.expo.io/guides/config-plugins/) which lets users add native modules that aren't in the Expo Go app to their native cloud builds and locally when [prebuilding](https://expo.fyi/prebuilding).
This is a [highly requested package](https://expo.canny.io/feature-requests/p/apple-healthkitgoogle-fit-data) so I've created the plugin personally.
Created a prebuild config plugin in `app.plugin.js`. Added a detailed docs page on how to use the plugin and the limitations.
- Run `npm pack` in the package
- Install the package in a managed Expo project `yarn add react-native-health@../react-native-health/react-native-health-1.7.2.tgz`
- Then add `react-native-health` to the plugins array and build the native app locally …

Created Expo config plugin

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
docs/getBloodAlcoholContentSamples.md
docs/getBloodGlucoseSamples.md
docs/getBodyFatPercentageSamples.md
docs/getBodyTemperatureSamples.md
docs/getCarbohydratesSamples.md
docs/getHeartRateSamples.md
docs/getHeartRateVariabilitySamples.md
docs/getHeightSamples.md
docs/getLeanBodyMassSamples.md
docs/getOxygenSaturationSamples.md
docs/getProteinSamples.md
docs/getRespiratoryRateSamples.md
docs/getRestingHeartRateSamples.md
docs/getVo2MaxSamples.md
docs/getWeightSamples.md
index.d.ts

This PR exposes [HealthKit Object UUID](https://developer.apple.com/documentation/healthkit/hkobject/1615721-uuid) in samples responses. This extra field would allow applications to be able to know deterministically if a value is different from one sync'ed before, which is handy for scenarios where the data is being stored by the application client or server-side. Otherwise, they'd have to rely on `startDate` / `endDate` to identify HK objects which might not be reliable.

Expose HealthKit Object UUID in samples responses

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m

We bumped into a problem where having 43k+ step entries over 10 years in Apple Health but we only wanted data from the past 7 days, yet the query took 2k+ ms. After playing with the `period` parameter I managed to get it down to 400ms, but I realised that the query unnecessarily fetches all the data available and then applies `startDate` and `endDate`.
This can be improved by changing the `NSPredicate` so that it includes the date condition. This got my query down to `<20ms`.
```
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"metadata.%K != YES AND %K >= %@ AND %K <= %@",
HKMetadataKeyWasUserEntered,
HKPredicateKeyPathEndDate, startDate,
HKPredicateKeyPathStartDate, endDate];
```
https://developer.apple.com/documentation/healthkit/hkquery/1614771-predicateforsa …

Performance fix for statistics queries

---

index.d.ts

This is TypeScript definition **hotfix**, saveBodyFatPercent is undefined, saveBodyFatPercentage is proper method name + ts linting in some places are not consistent

Typo in method definition + lint typescript

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Body.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Body.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
docs/README.md
docs/getLatestWaistCircumference.md
docs/getWaistCircumferenceSamples.md
docs/saveWaistCircumference.md
index.d.ts
src/constants/Permissions.js

This PR adds support for [waist circumference](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifierwaistcircumference/) to `react-native-health` library.

Add support for waist circumference

---

README.md
SUMMARY.md
docs/README.md
docs/getWalkingHeartRateAverage.md
docs/permissions.md
index.d.ts
src/constants/Permissions.js

This PR exposes the existing getWalkingHeartRateAverage method to JS.  The method existed already in Obj-C, and there was actually already a type definition for it in index.d.ts.  However, the permission was missing from Permissions.js and no documentation existed.
Fixes #119

Export WalkingHeartRateAverage in JS

---

index.d.ts

`getAnchoredWorkouts` callback function was typing the error param as `string`,
But using the library we realized that the actual error is an object with a `message` prop, this PR adds a interface for this error and change the type of error param.
The [function docs](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getAnchoredWorkouts.md) also shows `error` param as an Object.

fix(types): fix getAnchoredWorkouts error type

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m

Moves the query completion handlers off from the main queue to the `DISPATCH_QUEUE_PRIORITY_DEFAULT ` global dispatch queue to avoid blocking the UI thread.
See: 
- https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html
- https://reactnative.dev/docs/native-modules-ios#threading
Fixes #157

Moves query completion handlers off the main queue

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
SUMMARY.md
docs/README.md
docs/saveWalkingRunningDistance.md
index.d.ts

Currently there is no way to log walking + running distance activity. In order to log distance while running I've added this new method which is modeled after the other write functions such as `saveWeight` and `saveSteps`. I've verified it works as expected as well.
https://user-images.githubusercontent.com/290084/178244181-39c1bc98-3d2a-434a-9b1d-a9748b5d9c2b.mp4

feat: AppleHealthKit.saveWalkingRunningDistance

---

package.json

Bumps the [@expo/config-plugins](https://www.npmjs.com/package/@expo/config-plugins) to the latest version. The version currently used depends on a version of [@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom) (0.5.0) that is subject to a security advisory ([CVE-2021-32796](https://github.com/advisories/GHSA-5fg8-2547-mr8q)).
As far as I can tell there shouldn't be any backwards compatibility issues with the new version of `@expo/config-plugins` but I'm not an Expo expert.

Updates the @expo/config-plugins version

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
docs/getSleepSamples.md

Sleep samples on iOS 16.0 (released Monday) are currently showing up with an UNKNOWN value.
This is because iOS 16 and watchOS 9 introduced sleep stages. Users with Apple Watches who have upgraded to the latest version of iOS will no longer see sleep samples with an HKCategoryValueSleepAnalysisAsleep value -- instead they will see many different sleep samples with HKCategoryValueSleepAnalysisAsleepCore, HKCategoryValueSleepAnalysisAsleepDeep, HKCategoryValueSleepAnalysisAsleepREM, or HKCategoryValueSleepAnalysisAwake values. In the current code, these are all mapped to UNKNOWN.
This PR adds support for the new support for CORE/DEEP/REM/AWAKE sleepAnalysis types, while retaining support for ASLEEP (for any users on iOS 15 or previous, or with other wearables). It also updates the relevant …

Handle new sleep stage HKCategoryValues in iOS 16

---

docs/README.md

Current hyperlink doubles /docs and points to non-existing file
Typo edited

docs: fix getSamples method docs hyperlink

---

docs/getClinicalRecords.md

The clinical record type `VitalSignRecord` was missing from the list of possible types.

Add missing clinical record type VitalSignRecord

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
RCTAppleHealthKit/RCTAppleHealthKit.h
RCTAppleHealthKit/RCTAppleHealthKit.m

Adding the line [[RCTAppleHealthKit new] initializeBackgroundObservers:bridge]; causes the app to crash when opening
Error when sending event: healthKit:ActiveEnergyBurned:setup:success with body: {\n}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RCTAppleHealthKit, even though it's inherited from RCTEventEmitter

issue-201 possible fix

---

docs/background.md
example/App.tsx
example/index.js
example/ios/Podfile
example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj
example/ios/example/AppDelegate.m
example/ios/example/example.entitlements
example/package.json
example/yarn.lock
package.json

- Updated example app react and react-native version
- Fixed compilation error when example app is built on Apple Silicon 
- Added example of how to enable listeners
- Updated required react-native version on lib's package.json

Example app update

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Fitness.m
RCTAppleHealthKit/RCTAppleHealthKit+Queries.m

Lib currently crashes when trying to get statistical data without user permission. This happens because `startDate` and `endDate` fields on the query's response are `null` in this case, and the code crashes when trying to add them to an NSDictionary. Fixed by returning an error to js.
Fixes #97

Fix: Crash when getting statistical data without permissions

---

docs/getAnchoredWorkouts.md

Looks like the input argument lists the wrong property name in the documentation for getAnchoredWorkouts.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes getAnchoredWorkouts documentation

---

index.d.ts

Fixes two typescript errors from `index.d.ts` file.
**Changes**
- Remove unused import
- Add `undefined` to `RecordMetadata` index signature
**Output from Typescript compiler:**
**Unused import:**
**Index signature not including undefined:**
ping @GGGava @RuanAzevedo

Fix Typescript errors in index.d.ts

---

app.plugin.js
docs/Expo.md

The expo plugin doesn't have support for `NSHealthClinicalHealthRecordsShareUsageDescription`, so I added the support to also modify that from `app.config.js` 
I've also tested that the Info.plist has been modified correctly after running `expo prebuild`

added expo support to `NSHealthClinicalHealthRecordsShareUsageDescription` 

---

docs/Expo.md

Hi 👋
One thing I'd like to update and make it future-proof for Expo specific projects is to update the installation command from `expo install...` to `npx expo install...`. Since the latter refers to the new Expo CLI, which doesn't require any global package installation. For `expo install`, people will need to install the deprecated global cli (and we are not recommending that).
Also, update docs-related links.
Thank you!

docs: Update Expo.md

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Results.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Results.m
RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
RCTAppleHealthKit/RCTAppleHealthKit.m
docs/background.md
docs/deleteInsulinDeliverySample.md
docs/getInsulinDeliverySamples.md
docs/saveInsulinDeliverySample.md
index.d.ts
src/constants/Permissions.js

This PR adds support for "Insulin Delivery" samples, including fetch, save and delete. It also enables background observing for this type of sample.
Fixes #317

Support for Insulin Delivery samples

---

docs/getActiveEnergyBurned.md
docs/getBasalEnergyBurned.md

I and some of my colleagues used this library to get user's calories for a specific time period as we want to record people's workouts in our app. The problem that we faced was that we could not get the Total Calories from an Apple Watch workout. The description of getActiveEnergyBurned and getBasalEnergyBurned in docs were the same, so not knowing what 'basal' means we kind of ignored it. We wanted to obtain the total calories which is the sum of the two but were pointed on the wrong track due to the wording of the docs. I am sure others have had the same confusion and thus I wanted to improve the docs a little bit so that other people figure out faster the idea of active, resting and total calories.
Also, I added some of the options we needed but again, didn't know existed at the …

Get Energy Doc Fixes

---

RCTAppleHealthKit/RCTAppleHealthKit+Methods_Dietary.h
RCTAppleHealthKit/RCTAppleHealthKit+Methods_Dietary.m
RCTAppleHealthKit/RCTAppleHealthKit.m
README.md
docs/getFiberSamples.md
index.d.ts

This PR adds support for getting `fiber` values the same way as getting e.g. `protein`. Also the `README.md` was updated and docs added for the new `fiber` support.
Fixes #273

Add getFiberSamples

---

RCTAppleHealthKit/RCTAppleHealthKit+Queries.m
RCTAppleHealthKit/RCTAppleHealthKit+Utils.h
RCTAppleHealthKit/RCTAppleHealthKit+Utils.m
docs/getAnchoredWorkouts.md
index.d.ts

Adding duration and workout events to the response of the `getAnchoredWorkouts()` method.
- Duration returns the total duration covering all the samples that match the query.
- Workout events return's an array with multiple attributes like when the user has paused and/or resumed a workout.

Workout Events and Duration To getAnchoredWorkouts Method

---

RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
index.d.ts
src/constants/Permissions.js

We use react-native-health to ask users to accept HK permissions of metrics that we use in our Apple Watch app. In WatchOS9 'RunningSpeed' was released which will return the pace of the user while running outside. This PR exposes the new metric to the Permissions module of this library

feat: add HK RunningSpeed to permissions

---

example/App.tsx
index.ts
v2/RNHealthKitCore/HealthKitCore.xcodeproj/project.pbxproj
v2/RNHealthKitCore/HealthKitCore/Workout/Quantity.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutActivity.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutConfiguration.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutQueries.swift
v2/RNHealthKitCore/HealthKitCore/Workout/WorkoutSample.swift
v2/RNHealthKitCore/ReactNativeBridge/RNHealthKitWrapper.swift
v2/RNHealthKitCoreApp/RNHealthKitCoreApp/ContentView.swift

This PR includes the following changes: 
- Adds workout activity support. Now it's possible to fetch activity information from samples and save these activities on newly created workouts
- Adds support to multiple activities in a single workout. (E.g. `swimBikeRun`)
Fixes #
Fixes issue with `SwimBikeRun`, `Transition`, `UnderwaterDiving` raw values. Updated their values to the correct ones and added the new `UnderwaterDiving` case.

feat: Add activities info to workout samples
